
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: totality-godmode
spec:
  project: default
  source:
    repoURL: git@github.com:Agentcygroup/totality-godmode.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

